### ISSUE TITLE
Error converting the file

### ISSUE THREAD

**Issue by e2045** [ArtToledo/Convert-multiple-files#2]
Hi, i tried your example but i got this error:

The command "c:\Users\myUser\OneDrive" is either misspelled or could not be found.
Error: Error converting the file
    at c:\Users\myUser\OneDrive - myUser\Tool\node_modules\convert-multiple-files\lib\index.js:68:19
    at step (c:\Users\myUser\OneDrive - myUser\Tool\node_modules\convert-multiple-files\lib\index.js:33:23)
    at Object.next (c:\Users\myUser\OneDrive - myUser\Tool\node_modules\convert-multiple-files\lib\index.js:14:53)
    at c:\Users\myUser\OneDrive - myUser\Tool\node_modules\convert-multiple-files\lib\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\myUser\OneDrive - myUser\Tool\node_modules\convert-multiple-files\lib\index.js:4:12)
    at Object.convertWordFiles (c:\Users\myUser\OneDrive - myUser\Tool\node_modules\convert-multiple-files\lib\index.js:44:75)
    at test (c:\Users\myUser\OneDrive - myUser\Tool\listFiles.js:42:44)
    at Object.<anonymous> (c:\Users\myUser\OneDrive - myUser\Tool\listFiles.js:31:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

I checked that path of folder was right. I don't know how to handle this issue. Could you help me? Thank you in advance.

**Comment by ArtToledo** [comment]
Hello, first sorry for my bad English.

Could you send me the part of the code where you make the conversion call? What type of conversion are you using? I await the information so that we can arrive at the solution as soon as possible.

**Comment by e2045** [comment]
Hello,
thank you for your reply. Here is my code: 

```
async function test() {
    const path = require('path');
    const convertMF = require('convert-multiple-files');
    // Return promise => convertWordFiles(path of the file to be converted, convertTo, outputDir)
    try {
        const pathOutput = await convertMF.convertWordFiles(path.resolve(__dirname, 'teste.docx'), 'pdf', path.resolve(__dirname));
        return pathOutput;
    } catch (error) {
        console.log(error)
    }
}
test()

```

I used try catch block because there was error. It recommended that I should use try catch block.

**Comment by ArtToledo** [comment]
Hello, please run the code below, I believe it will work:

`const path = require('path');
const convert = require('convert-multiple-files');

async function test() {
  // Return promise => convertWordFiles(path of the file to be converted, convertTo, outputDir)
  try {
    const pathOutput = await convert.convertWordFiles(path.resolve(__dirname, 'teste.docx'), 'pdf', path.resolve(__dirname));
    return pathOutput;
  } catch (error) {
      console.log(error)
  }
}
test()`

**Comment by e2045** [comment]
thank you for your reply. But the same error still occurs.

**Comment by ArtToledo** [comment]
Seriously? I believe then that this file cannot be found, there are no other reasons, we can do one more test to find the exact error log, but first ask me a question, is this file local or is it in some cloud storage?
